config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#ndestroy'
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :destroy, :update, :show]
  
  def index 
    @articles = Article.paginate(:page => params[:page], :per_page => 5)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(articles_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end
  
  def show
    
  end
  
  def edit 
    
  end
  
  def update
    if @article.update(articles_params)
      flash[:success] = "Article was successfully updated"
      redirect_to articles_path
    else
      render :edit
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private 
    def set_article
      @article = Article.find(params[:id])
    end
    
    def articles_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  
  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    
  end
  
  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |a| %>
  <div class="container">
    <div class="row center">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-preview  well well-lg">
          <h4 class="post-title"><%= link_to a.title, article_path(a) %></h4>
          <h5 class="post-subtitle"><%= a.description %></h5><br>
          <div class="article-meta-details">
            <small>Created by: <%= a.user.username if a.user %>,
                   <%= time_ago_in_words(a.created_at) %> ago,
                   last updated: <%= time_ago_in_words(a.updated_at) %> ago
            </small>
          </div>
          <%= link_to 'Show', article_path(a), class: "btn btn-primary btn-xs", id: "color-change" %>
          <%= link_to 'Edit', edit_article_path(a), class: "btn btn-primary btn-xs", id: "color-change" %>
          <%= link_to 'Delete', a, method: :delete, data: { confirm: "Are You Sure!!!" }, class: "btn btn-danger btn-xs", id: "color-change" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container center">
  <%= render 'shared/errors', obj: @article %>
  <div class="row">
    <div class="col-sx-12">
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of the Article" %>
          </div>
        </div>
         <div class="center">
            <%= f.submit class: "btn btn-primary" %>
            <%= link_to 'Cancel', articles_path, class: "btn btn-danger" %>
          </div>
      <% end %>
      </div>
  </div>
</div>
  

app/views/articles/edit.html.erb
<h1 align="center">Edit an article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container center">
  <h1>Article Listing</h1>
  
  <div class="center pagination">
    <%= will_paginate @articles %>
  </div>

  <%= render 'article', obj: @articles %>


  <%= link_to 'CREATE ARTICLE', new_article_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/articles/new.html.erb
<h1 align= "center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><strong>Title:</strong><%= @article.title %></h2>


<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <div class="row center">
      Created by: <br>
      <%= link_to gravatar_for(@article.user), user_path(@article.user) %> <br>
      <%= link_to @article.user.username, user_path(@article.user) %>  <br>
      <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li><br>
    </div>
  <% end %>
  
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-action">
    <%= link_to 'View All Articles', articles_path, class: "btn btn-success btn-xs" %>
    <%= link_to 'Edit This Article', edit_article_path(@article), class: "btn btn-primary btn-xs" %>
    <%= link_to 'Delete This Article', @article, method: :delete, data: { confirm: "Are You Sure!!!" }, class: "btn btn-danger btn-xs", id: "color-change" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
          <a class="color-change" href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
        <li>
          <a class="color-change" href="#">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </li>
        <li>
            <a class="color-change" href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; RIAZ ALPHA BLOG 2016</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p><%= msg %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">Alpha Blog</a>-->
      <%= link_to 'Alpha Blog', root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Create Article', new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log In', login_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  
  <div class="container">
    <%= yield %>  
  </div>
  
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page</h1>

<%= link_to 'Home', root_path, class: "btn btn-primary" %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 id="white-color">Alpha Blog</h1>
  <%= link_to 'Sign up Now!!!', signup_path , class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:-
          </h2>
        </div>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container center">
  <%= render 'shared/errors', obj: @user %>
  <div class="row">
    <div class="col-sx-12">
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :username %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :email %>
          </div>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", placeholder: "Email Address" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :password %>
          </div>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
          </div>
        </div>
         <div class="center">
            <%= f.submit(@user.new_record?? "Sign Up" : "Update Account", class: "btn btn-primary") %>
            <%= link_to 'Cancel request and return to the article listing', articles_path, class: "btn btn-danger" %>
          </div>
      <% end %>
      </div>
  </div>
</div>
  

app/views/users/edit.html.erb
<h1 align="center">Update user information for the Alpha Blog</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Bloggers</h1>

<div class="center">
  <h1>List of Users</h1>
  <%= will_paginate @users %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li><%= link_to user.username, user_path(user) %></li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up for the Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
    </div>
  </div>
  <div class="center">
    <h4><%= @user.username %>'s articles</h4>
    <%= will_paginate @user_articles %>
    <%= render 'articles/article', obj: @user_articles %>
    <%= will_paginate @user_articles %>
  </div>